name: test
on:
  - push
  - pull_request
    
defaults:
  run:
    shell: bash
    
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        arch: [x64, arm64]
        exclude:
          - os: ubuntu-latest
            arch: arm64
          - os: windows-latest
            arch: arm64
          - os: macos-latest
            arch: x64
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: JuliaInterop/libcxxwrap-julia
          path: libcxxwrap
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Build libcxxwrap-julia
        run: |
          mkdir build-libcxxwrap && cd build-libcxxwrap
          cmake -DCMAKE_INSTALL_PREFIX=$HOME/install -DJLCXX_BUILD_EXAMPLES=OFF -DCMAKE_BUILD_TYPE=Debug ../libcxxwrap
          VERBOSE=ON cmake --build . --config Debug --target install
      - name: Build and test
        run: |
          mkdir build && cd build
          cmake -DCMAKE_PREFIX_PATH=$HOME/install -DJLQML_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug  ..
          VERBOSE=ON cmake --build . --config Debug
          ctest -C Debug -V --output-on-failure
